
#pragma once
#include <array>
constexpr const char* group_cache_select_sm_90_bf16 = R"(_group_cache_select)";
constexpr std::array<std::array<int, 3>, 2> group_cache_select_sm_90_bf16_INPUT_DIM_ARRAY = {{ 
    { 1, 128, 1 },  // Index 0
    { 1, 256, 1 }   // Index 1
    }};
constexpr std::array<int, 2> group_cache_select_sm_90_bf16_BLOCK_M_ARRAY{ 1, 1 };
constexpr std::array<int, 2> group_cache_select_sm_90_bf16_BLOCK_N_ARRAY{ 32, 32 };
constexpr std::array<int, 2> group_cache_select_sm_90_bf16_BLOCK_K_ARRAY{ 1, 1 };
constexpr std::array<int, 2> group_cache_select_sm_90_bf16_BLOCK_SIZE{ 32, 32 };
constexpr std::array<int, 2> group_cache_select_sm_90_bf16_SHARED_MEM_BYTES{ 0, 0 };
constexpr std::array<const char*, 2> group_cache_select_sm_90_bf16_PTX_ARRAY = {
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<23>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<43>;
	.reg .b64 	%rd<76>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r16, [_group_cache_select_param_4];
	ld.param.b64 	%rd29, [_group_cache_select_param_1];
	ld.param.b64 	%rd30, [_group_cache_select_param_2];
$L__tmp0:
	.loc	1 29 29                         // group_select.py:29:29
	mov.u32 	%r21, %ctaid.x;
	ld.param.b64 	%rd31, [_group_cache_select_param_3];
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r22, %ctaid.y;
	.loc	1 33 37                         // group_select.py:33:37
	mad.wide.u32 	%rd23, %r22, 8, %rd31;
	.loc	1 33 23                         // group_select.py:33:23
	// begin inline asm
	mov.u64 %rd22, 0x0;
	ld.global.b64 { %rd22 }, [ %rd23 + 0 ];
	// end inline asm
	.loc	1 34 37                         // group_select.py:34:37
	mul.wide.u32 	%rd32, %r21, 8;
	add.s64 	%rd25, %rd29, %rd32;
	.loc	1 34 20                         // group_select.py:34:20
	// begin inline asm
	mov.u64 %rd24, 0x0;
	ld.global.b64 { %rd24 }, [ %rd25 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	add.s64 	%rd27, %rd30, %rd32;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd26, 0x0;
	ld.global.b64 { %rd26 }, [ %rd27 + 0 ];
	// end inline asm
	.loc	1 41 39                         // group_select.py:41:39
	setp.lt.s32 	%p1, %r16, 1;
	@%p1 bra 	$L__BB0_13;
// %bb.1:                               // %.lr.ph
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r18, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r18, 1;
	@%p2 bra 	$L__BB0_13;
// %bb.2:                               // %.lr.ph.split.us
	ld.param.b32 	%r19, [_group_cache_select_param_5];
	cvt.s64.s32 	%rd3, %r19;
	cvt.u32.u64 	%r27, %rd3;
	setp.gt.s32 	%p3, %r27, 0;
	@%p3 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_3;
$L__BB0_5:                              // %.lr.ph31.us.us.us.preheader
	ld.param.b32 	%r17, [_group_cache_select_param_6];
	ld.param.b64 	%rd28, [_group_cache_select_param_0];
	mov.u32 	%r23, %ctaid.z;
	ld.param.b32 	%r24, [_group_cache_select_param_7];
	cvt.s64.s32 	%rd33, %r24;
	cvt.s64.s32 	%rd34, %r18;
	mul.wide.s32 	%rd35, %r17, %r19;
	mul.lo.s64 	%rd36, %rd35, %rd33;
	mul.lo.s64 	%rd37, %rd36, %rd34;
	mul.lo.s32 	%r1, %r18, %r24;
	mul.lo.s32 	%r25, %r1, %r23;
	cvt.s64.s32 	%rd38, %r25;
	mad.lo.s64 	%rd4, %rd37, %rd22, %rd38;
	mov.u32 	%r2, %tid.x;
	and.b32 	%r3, %r2, 31;
	mul.lo.s32 	%r26, %r19, %r22;
	mad.wide.s32 	%rd5, %r26, 4, %rd28;
	mul.lo.s32 	%r4, %r1, %r17;
	and.b32 	%r5, %r2, 96;
	.loc	1 41 39                         // group_select.py:41:39
	cvt.u64.u32 	%rd6, %r16;
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r30, %r27, -1;
	mul.lo.s32 	%r6, %r4, %r30;
	add.s64 	%rd8, %rd3, -1;
	mov.b64 	%rd71, 0;
	setp.eq.b32 	%p10, %r5, 0;
$L__BB0_6:                              // %.lr.ph31.us.us.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_7 Depth 2
                                        //       Child Loop BB0_8 Depth 3
                                        //       Child Loop BB0_10 Depth 3
	.loc	1 45 44                         // group_select.py:45:44
	cvt.u32.u64 	%r32, %rd71;
	mul.lo.s32 	%r33, %r18, %r32;
	.loc	1 45 37                         // group_select.py:45:37
	cvt.s64.s32 	%rd40, %r33;
	add.s64 	%rd10, %rd4, %rd40;
	mov.b32 	%r31, 0;
	mov.b32 	%r39, %r31;
$L__BB0_7:                              // %.lr.ph.us.us.us.us.us
                                        //   Parent Loop BB0_6 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_8 Depth 3
                                        //       Child Loop BB0_10 Depth 3
	.loc	1 47 50                         // group_select.py:47:50
	or.b32 	%r8, %r39, %r3;
	.loc	1 49 48                         // group_select.py:49:48
	mul.wide.s32 	%rd42, %r8, 2;
	add.s64 	%rd11, %rd24, %rd42;
	add.s64 	%rd12, %rd26, %rd42;
	mov.b64 	%rd75, 0;
	setp.lt.s32 	%p9, %r8, %r18;
	mov.b64 	%rd74, %rd5;
	mov.b32 	%r41, %r31;
$L__BB0_8:                              //   Parent Loop BB0_6 Depth=1
                                        //     Parent Loop BB0_7 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 52 33                         // group_select.py:52:33
	// begin inline asm
	mov.u32 %r35, 0x0;
	ld.global.b32 { %r35 }, [ %rd74 + 0 ];
	// end inline asm
	.loc	1 54 35                         // group_select.py:54:35
	cvt.s64.s32 	%rd48, %r35;
	setp.lt.s64 	%p11, %rd75, %rd48;
	.loc	1 56 84                         // group_select.py:56:84
	mul.lo.s32 	%r36, %r4, %r35;
	.loc	1 56 44                         // group_select.py:56:44
	cvt.s64.s32 	%rd49, %r36;
	add.s64 	%rd50, %rd10, %rd49;
	.loc	1 57 48                         // group_select.py:57:48
	cvt.s64.s32 	%rd51, %r41;
	add.s64 	%rd52, %rd10, %rd51;
	.loc	1 60 65                         // group_select.py:60:65
	shl.b64 	%rd53, %rd50, 1;
	add.s64 	%rd44, %rd11, %rd53;
	.loc	1 60 99                         // group_select.py:60:99
	and.pred 	%p5, %p9, %p11;
	.loc	1 60 86                         // group_select.py:60:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p5 ld.global.b16 { %rs1 }, [ %rd44 + 0 ];
	// end inline asm
	.loc	1 61 60                         // group_select.py:61:60
	shl.b64 	%rd54, %rd52, 1;
	add.s64 	%rd45, %rd11, %rd54;
	.loc	1 61 90                         // group_select.py:61:90
	and.pred 	%p6, %p10, %p5;
	// begin inline asm
	@%p6 st.global.b16 [ %rd45 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 62 65                         // group_select.py:62:65
	add.s64 	%rd46, %rd12, %rd53;
	.loc	1 62 86                         // group_select.py:62:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p5 ld.global.b16 { %rs3 }, [ %rd46 + 0 ];
	// end inline asm
	.loc	1 63 60                         // group_select.py:63:60
	add.s64 	%rd47, %rd12, %rd54;
	.loc	1 63 90                         // group_select.py:63:90
	// begin inline asm
	@%p6 st.global.b16 [ %rd47 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 49 48                         // group_select.py:49:48
	add.s64 	%rd75, %rd75, 1;
	add.s32 	%r41, %r41, %r4;
	add.s64 	%rd74, %rd74, 4;
	setp.ne.b64 	%p12, %rd3, %rd75;
	@%p12 bra 	$L__BB0_8;
// %bb.9:                               // %..preheader_crit_edge.us.us.us.us.us.preheader
                                        //   in Loop: Header=BB0_7 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd73, 0;
	mov.b64 	%rd72, %rd8;
	mov.b32 	%r40, %r6;
$L__BB0_10:                             // %..preheader_crit_edge.us.us.us.us.us
                                        //   Parent Loop BB0_6 Depth=1
                                        //     Parent Loop BB0_7 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd61, %rd73;
	add.s64 	%rd62, %rd3, %rd61;
	.loc	1 68 73                         // group_select.py:68:73
	shl.b64 	%rd63, %rd62, 2;
	add.s64 	%rd56, %rd5, %rd63;
	.loc	1 68 33                         // group_select.py:68:33
	// begin inline asm
	mov.u32 %r37, 0x0;
	ld.global.b32 { %r37 }, [ %rd56 + 0 ];
	// end inline asm
	.loc	1 70 35                         // group_select.py:70:35
	cvt.s64.s32 	%rd64, %r37;
	setp.gt.s64 	%p19, %rd72, %rd64;
	.loc	1 72 84                         // group_select.py:72:84
	mul.lo.s32 	%r38, %r4, %r37;
	.loc	1 72 44                         // group_select.py:72:44
	cvt.s64.s32 	%rd65, %r38;
	add.s64 	%rd66, %rd10, %rd65;
	.loc	1 73 48                         // group_select.py:73:48
	cvt.s64.s32 	%rd67, %r40;
	add.s64 	%rd68, %rd10, %rd67;
	.loc	1 75 65                         // group_select.py:75:65
	shl.b64 	%rd69, %rd66, 1;
	add.s64 	%rd57, %rd11, %rd69;
	.loc	1 75 99                         // group_select.py:75:99
	and.pred 	%p13, %p9, %p19;
	.loc	1 75 86                         // group_select.py:75:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p13 ld.global.b16 { %rs5 }, [ %rd57 + 0 ];
	// end inline asm
	.loc	1 76 60                         // group_select.py:76:60
	shl.b64 	%rd70, %rd68, 1;
	add.s64 	%rd58, %rd11, %rd70;
	.loc	1 76 90                         // group_select.py:76:90
	and.pred 	%p14, %p10, %p13;
	// begin inline asm
	@%p14 st.global.b16 [ %rd58 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 77 65                         // group_select.py:77:65
	add.s64 	%rd59, %rd12, %rd69;
	.loc	1 77 86                         // group_select.py:77:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p13 ld.global.b16 { %rs7 }, [ %rd59 + 0 ];
	// end inline asm
	.loc	1 78 60                         // group_select.py:78:60
	add.s64 	%rd60, %rd12, %rd70;
	.loc	1 78 90                         // group_select.py:78:90
	// begin inline asm
	@%p14 st.global.b16 [ %rd60 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 65 49                         // group_select.py:65:49
	add.s64 	%rd73, %rd73, 1;
	sub.s32 	%r40, %r40, %r4;
	add.s64 	%rd72, %rd72, -1;
	setp.eq.b64 	%p20, %rd3, %rd73;
	@%p20 bra 	$L__BB0_11;
	bra.uni 	$L__BB0_10;
$L__BB0_11:                             // %._crit_edge.us.us.us.us.us
                                        //   in Loop: Header=BB0_7 Depth=2
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r39, %r39, 32;
	setp.lt.s32 	%p21, %r39, %r18;
	@%p21 bra 	$L__BB0_7;
// %bb.12:                              // %._crit_edge32.split.us.us.us.split.us.us
                                        //   in Loop: Header=BB0_6 Depth=1
	.loc	1 41 39                         // group_select.py:41:39
	add.s64 	%rd71, %rd71, 1;
	setp.eq.b64 	%p22, %rd71, %rd6;
	@%p22 bra 	$L__BB0_13;
	bra.uni 	$L__BB0_6;
$L__BB0_3:                              // %.preheader.us47.preheader
	.loc	1 0 39                          // group_select.py:0:39
	mov.b32 	%r42, 0;
$L__BB0_4:                              // %.preheader.us47
                                        // =>This Inner Loop Header: Depth=1
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r42, %r42, 32;
	setp.lt.s32 	%p4, %r42, %r18;
	@%p4 bra 	$L__BB0_4;
$L__BB0_13:                             // %._crit_edge
	.loc	1 41 4                          // group_select.py:41:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/wangyifan/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 119
.b8 97
.b8 110
.b8 103
.b8 121
.b8 105
.b8 102
.b8 97
.b8 110
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})" ,  // Index 0
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<23>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<43>;
	.reg .b64 	%rd<76>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r16, [_group_cache_select_param_4];
	ld.param.b64 	%rd29, [_group_cache_select_param_1];
	ld.param.b64 	%rd30, [_group_cache_select_param_2];
$L__tmp0:
	.loc	1 29 29                         // group_select.py:29:29
	mov.u32 	%r21, %ctaid.x;
	ld.param.b64 	%rd31, [_group_cache_select_param_3];
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r22, %ctaid.y;
	.loc	1 33 37                         // group_select.py:33:37
	mad.wide.u32 	%rd23, %r22, 8, %rd31;
	.loc	1 33 23                         // group_select.py:33:23
	// begin inline asm
	mov.u64 %rd22, 0x0;
	ld.global.b64 { %rd22 }, [ %rd23 + 0 ];
	// end inline asm
	.loc	1 34 37                         // group_select.py:34:37
	mul.wide.u32 	%rd32, %r21, 8;
	add.s64 	%rd25, %rd29, %rd32;
	.loc	1 34 20                         // group_select.py:34:20
	// begin inline asm
	mov.u64 %rd24, 0x0;
	ld.global.b64 { %rd24 }, [ %rd25 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	add.s64 	%rd27, %rd30, %rd32;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd26, 0x0;
	ld.global.b64 { %rd26 }, [ %rd27 + 0 ];
	// end inline asm
	.loc	1 41 39                         // group_select.py:41:39
	setp.lt.s32 	%p1, %r16, 1;
	@%p1 bra 	$L__BB0_13;
// %bb.1:                               // %.lr.ph
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r18, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r18, 1;
	@%p2 bra 	$L__BB0_13;
// %bb.2:                               // %.lr.ph.split.us
	ld.param.b32 	%r19, [_group_cache_select_param_5];
	cvt.s64.s32 	%rd3, %r19;
	cvt.u32.u64 	%r27, %rd3;
	setp.gt.s32 	%p3, %r27, 0;
	@%p3 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_3;
$L__BB0_5:                              // %.lr.ph31.us.us.us.preheader
	ld.param.b32 	%r17, [_group_cache_select_param_6];
	ld.param.b64 	%rd28, [_group_cache_select_param_0];
	mov.u32 	%r23, %ctaid.z;
	ld.param.b32 	%r24, [_group_cache_select_param_7];
	cvt.s64.s32 	%rd33, %r24;
	cvt.s64.s32 	%rd34, %r18;
	mul.wide.s32 	%rd35, %r17, %r19;
	mul.lo.s64 	%rd36, %rd35, %rd33;
	mul.lo.s64 	%rd37, %rd36, %rd34;
	mul.lo.s32 	%r1, %r18, %r24;
	mul.lo.s32 	%r25, %r1, %r23;
	cvt.s64.s32 	%rd38, %r25;
	mad.lo.s64 	%rd4, %rd37, %rd22, %rd38;
	mov.u32 	%r2, %tid.x;
	and.b32 	%r3, %r2, 31;
	mul.lo.s32 	%r26, %r19, %r22;
	mad.wide.s32 	%rd5, %r26, 4, %rd28;
	mul.lo.s32 	%r4, %r1, %r17;
	and.b32 	%r5, %r2, 96;
	.loc	1 41 39                         // group_select.py:41:39
	cvt.u64.u32 	%rd6, %r16;
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r30, %r27, -1;
	mul.lo.s32 	%r6, %r4, %r30;
	add.s64 	%rd8, %rd3, -1;
	mov.b64 	%rd71, 0;
	setp.eq.b32 	%p10, %r5, 0;
$L__BB0_6:                              // %.lr.ph31.us.us.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_7 Depth 2
                                        //       Child Loop BB0_8 Depth 3
                                        //       Child Loop BB0_10 Depth 3
	.loc	1 45 44                         // group_select.py:45:44
	cvt.u32.u64 	%r32, %rd71;
	mul.lo.s32 	%r33, %r18, %r32;
	.loc	1 45 37                         // group_select.py:45:37
	cvt.s64.s32 	%rd40, %r33;
	add.s64 	%rd10, %rd4, %rd40;
	mov.b32 	%r31, 0;
	mov.b32 	%r39, %r31;
$L__BB0_7:                              // %.lr.ph.us.us.us.us.us
                                        //   Parent Loop BB0_6 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_8 Depth 3
                                        //       Child Loop BB0_10 Depth 3
	.loc	1 47 50                         // group_select.py:47:50
	or.b32 	%r8, %r39, %r3;
	.loc	1 49 48                         // group_select.py:49:48
	mul.wide.s32 	%rd42, %r8, 2;
	add.s64 	%rd11, %rd24, %rd42;
	add.s64 	%rd12, %rd26, %rd42;
	mov.b64 	%rd75, 0;
	setp.lt.s32 	%p9, %r8, %r18;
	mov.b64 	%rd74, %rd5;
	mov.b32 	%r41, %r31;
$L__BB0_8:                              //   Parent Loop BB0_6 Depth=1
                                        //     Parent Loop BB0_7 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 52 33                         // group_select.py:52:33
	// begin inline asm
	mov.u32 %r35, 0x0;
	ld.global.b32 { %r35 }, [ %rd74 + 0 ];
	// end inline asm
	.loc	1 54 35                         // group_select.py:54:35
	cvt.s64.s32 	%rd48, %r35;
	setp.lt.s64 	%p11, %rd75, %rd48;
	.loc	1 56 84                         // group_select.py:56:84
	mul.lo.s32 	%r36, %r4, %r35;
	.loc	1 56 44                         // group_select.py:56:44
	cvt.s64.s32 	%rd49, %r36;
	add.s64 	%rd50, %rd10, %rd49;
	.loc	1 57 48                         // group_select.py:57:48
	cvt.s64.s32 	%rd51, %r41;
	add.s64 	%rd52, %rd10, %rd51;
	.loc	1 60 65                         // group_select.py:60:65
	shl.b64 	%rd53, %rd50, 1;
	add.s64 	%rd44, %rd11, %rd53;
	.loc	1 60 99                         // group_select.py:60:99
	and.pred 	%p5, %p9, %p11;
	.loc	1 60 86                         // group_select.py:60:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p5 ld.global.b16 { %rs1 }, [ %rd44 + 0 ];
	// end inline asm
	.loc	1 61 60                         // group_select.py:61:60
	shl.b64 	%rd54, %rd52, 1;
	add.s64 	%rd45, %rd11, %rd54;
	.loc	1 61 90                         // group_select.py:61:90
	and.pred 	%p6, %p10, %p5;
	// begin inline asm
	@%p6 st.global.b16 [ %rd45 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 62 65                         // group_select.py:62:65
	add.s64 	%rd46, %rd12, %rd53;
	.loc	1 62 86                         // group_select.py:62:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p5 ld.global.b16 { %rs3 }, [ %rd46 + 0 ];
	// end inline asm
	.loc	1 63 60                         // group_select.py:63:60
	add.s64 	%rd47, %rd12, %rd54;
	.loc	1 63 90                         // group_select.py:63:90
	// begin inline asm
	@%p6 st.global.b16 [ %rd47 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 49 48                         // group_select.py:49:48
	add.s64 	%rd75, %rd75, 1;
	add.s32 	%r41, %r41, %r4;
	add.s64 	%rd74, %rd74, 4;
	setp.ne.b64 	%p12, %rd3, %rd75;
	@%p12 bra 	$L__BB0_8;
// %bb.9:                               // %..preheader_crit_edge.us.us.us.us.us.preheader
                                        //   in Loop: Header=BB0_7 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd73, 0;
	mov.b64 	%rd72, %rd8;
	mov.b32 	%r40, %r6;
$L__BB0_10:                             // %..preheader_crit_edge.us.us.us.us.us
                                        //   Parent Loop BB0_6 Depth=1
                                        //     Parent Loop BB0_7 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd61, %rd73;
	add.s64 	%rd62, %rd3, %rd61;
	.loc	1 68 73                         // group_select.py:68:73
	shl.b64 	%rd63, %rd62, 2;
	add.s64 	%rd56, %rd5, %rd63;
	.loc	1 68 33                         // group_select.py:68:33
	// begin inline asm
	mov.u32 %r37, 0x0;
	ld.global.b32 { %r37 }, [ %rd56 + 0 ];
	// end inline asm
	.loc	1 70 35                         // group_select.py:70:35
	cvt.s64.s32 	%rd64, %r37;
	setp.gt.s64 	%p19, %rd72, %rd64;
	.loc	1 72 84                         // group_select.py:72:84
	mul.lo.s32 	%r38, %r4, %r37;
	.loc	1 72 44                         // group_select.py:72:44
	cvt.s64.s32 	%rd65, %r38;
	add.s64 	%rd66, %rd10, %rd65;
	.loc	1 73 48                         // group_select.py:73:48
	cvt.s64.s32 	%rd67, %r40;
	add.s64 	%rd68, %rd10, %rd67;
	.loc	1 75 65                         // group_select.py:75:65
	shl.b64 	%rd69, %rd66, 1;
	add.s64 	%rd57, %rd11, %rd69;
	.loc	1 75 99                         // group_select.py:75:99
	and.pred 	%p13, %p9, %p19;
	.loc	1 75 86                         // group_select.py:75:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p13 ld.global.b16 { %rs5 }, [ %rd57 + 0 ];
	// end inline asm
	.loc	1 76 60                         // group_select.py:76:60
	shl.b64 	%rd70, %rd68, 1;
	add.s64 	%rd58, %rd11, %rd70;
	.loc	1 76 90                         // group_select.py:76:90
	and.pred 	%p14, %p10, %p13;
	// begin inline asm
	@%p14 st.global.b16 [ %rd58 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 77 65                         // group_select.py:77:65
	add.s64 	%rd59, %rd12, %rd69;
	.loc	1 77 86                         // group_select.py:77:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p13 ld.global.b16 { %rs7 }, [ %rd59 + 0 ];
	// end inline asm
	.loc	1 78 60                         // group_select.py:78:60
	add.s64 	%rd60, %rd12, %rd70;
	.loc	1 78 90                         // group_select.py:78:90
	// begin inline asm
	@%p14 st.global.b16 [ %rd60 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 65 49                         // group_select.py:65:49
	add.s64 	%rd73, %rd73, 1;
	sub.s32 	%r40, %r40, %r4;
	add.s64 	%rd72, %rd72, -1;
	setp.eq.b64 	%p20, %rd3, %rd73;
	@%p20 bra 	$L__BB0_11;
	bra.uni 	$L__BB0_10;
$L__BB0_11:                             // %._crit_edge.us.us.us.us.us
                                        //   in Loop: Header=BB0_7 Depth=2
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r39, %r39, 32;
	setp.lt.s32 	%p21, %r39, %r18;
	@%p21 bra 	$L__BB0_7;
// %bb.12:                              // %._crit_edge32.split.us.us.us.split.us.us
                                        //   in Loop: Header=BB0_6 Depth=1
	.loc	1 41 39                         // group_select.py:41:39
	add.s64 	%rd71, %rd71, 1;
	setp.eq.b64 	%p22, %rd71, %rd6;
	@%p22 bra 	$L__BB0_13;
	bra.uni 	$L__BB0_6;
$L__BB0_3:                              // %.preheader.us47.preheader
	.loc	1 0 39                          // group_select.py:0:39
	mov.b32 	%r42, 0;
$L__BB0_4:                              // %.preheader.us47
                                        // =>This Inner Loop Header: Depth=1
	.loc	1 46 38                         // group_select.py:46:38
	add.s32 	%r42, %r42, 32;
	setp.lt.s32 	%p4, %r42, %r18;
	@%p4 bra 	$L__BB0_4;
$L__BB0_13:                             // %._crit_edge
	.loc	1 41 4                          // group_select.py:41:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/wangyifan/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 119
.b8 97
.b8 110
.b8 103
.b8 121
.b8 105
.b8 102
.b8 97
.b8 110
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})"    // Index 1
    };
    
// Real 6-dimensional input configurations for group_cache_select
// [BATCH_SIZE, BEAM_SIZE, HEAD_NUM, HEAD_DIM, LAYER_NUM, MAX_DECODE_STEP]
// constexpr std::array<std::array<int, 6>, 2> GROUP_CACHE_SELECT_SM_90_bf16_REAL_DIMS = {{
//     {1, 128, 8, 128, 1, 2}, {1, 256, 8, 128, 1, 2}
// }};
