
#pragma once
#include <array>
constexpr const char* group_cache_select_sm_90_bf16 = R"(_group_cache_select)";
constexpr std::array<std::array<int, 3>, 5> group_cache_select_sm_90_bf16_INPUT_DIM_ARRAY = {{ 
    { 1, 128, 1 },  // Index 0
    { 1, 256, 1 },  // Index 1
    { 1, 512, 1 },  // Index 2
    { 1, 1024, 1 },  // Index 3
    { 1, 2048, 32 }   // Index 4
    }};
constexpr std::array<int, 5> group_cache_select_sm_90_bf16_BLOCK_M_ARRAY{ 1, 1, 1, 1, 1 };
constexpr std::array<int, 5> group_cache_select_sm_90_bf16_BLOCK_N_ARRAY{ 32, 32, 32, 32, 32 };
constexpr std::array<int, 5> group_cache_select_sm_90_bf16_BLOCK_K_ARRAY{ 1, 1, 1, 1, 1 };
constexpr std::array<int, 5> group_cache_select_sm_90_bf16_BLOCK_SIZE{ 32, 32, 32, 32, 32 };
constexpr std::array<int, 5> group_cache_select_sm_90_bf16_SHARED_MEM_BYTES{ 0, 0, 0, 0, 0 };
constexpr std::array<const char*, 5> group_cache_select_sm_90_bf16_PTX_ARRAY = {
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<53>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r26, [_group_cache_select_param_4];
	ld.param.b64 	%rd23, [_group_cache_select_param_1];
$L__tmp0:
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd24, [_group_cache_select_param_2];
	.loc	1 31 29                         // group_select.py:31:29
	mov.u32 	%r33, %ctaid.y;
	ld.param.b64 	%rd25, [_group_cache_select_param_3];
	.loc	1 34 37                         // group_select.py:34:37
	mad.wide.u32 	%rd17, %r33, 4, %rd25;
	.loc	1 34 23                         // group_select.py:34:23
	// begin inline asm
	mov.u32 %r31, 0x0;
	ld.global.b32 { %r31 }, [ %rd17 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	mul.wide.u32 	%rd26, %r32, 8;
	add.s64 	%rd19, %rd23, %rd26;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd18, 0x0;
	ld.global.b64 { %rd18 }, [ %rd19 + 0 ];
	// end inline asm
	.loc	1 36 37                         // group_select.py:36:37
	add.s64 	%rd21, %rd24, %rd26;
	.loc	1 36 20                         // group_select.py:36:20
	// begin inline asm
	mov.u64 %rd20, 0x0;
	ld.global.b64 { %rd20 }, [ %rd21 + 0 ];
	// end inline asm
	.loc	1 42 39                         // group_select.py:42:39
	setp.lt.s32 	%p1, %r26, 1;
	@%p1 bra 	$L__BB0_7;
// %bb.1:                               // %.lr.ph25
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r30, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r30, 1;
	@%p2 bra 	$L__BB0_7;
// %bb.2:                               // %.lr.ph22.us.preheader
	ld.param.b32 	%r29, [_group_cache_select_param_7];
	ld.param.b32 	%r28, [_group_cache_select_param_6];
	ld.param.b32 	%r27, [_group_cache_select_param_5];
	ld.param.b64 	%rd22, [_group_cache_select_param_0];
	mov.u32 	%r1, %ctaid.z;
	mul.lo.s32 	%r34, %r28, %r27;
	mad.lo.s32 	%r3, %r34, %r31, %r1;
	mul.lo.s32 	%r4, %r3, %r29;
	mov.u32 	%r5, %tid.x;
	and.b32 	%r6, %r5, 31;
	mul.lo.s32 	%r35, %r27, %r33;
	mad.wide.s32 	%rd3, %r35, 4, %rd22;
	mul.lo.s32 	%r7, %r29, %r28;
	and.b32 	%r8, %r5, 96;
	.loc	1 47 38                         // group_select.py:47:38
	cvt.s64.s32 	%rd4, %r27;
	cvt.u64.u32 	%rd5, %r27;
	mul.lo.s32 	%r37, %r30, %r29;
	mul.lo.s32 	%r49, %r37, %r3;
	mul.lo.s32 	%r10, %r37, %r28;
	mad.lo.s32 	%r38, %r27, %r31, %r27;
	add.s32 	%r39, %r38, -1;
	mad.lo.s32 	%r40, %r28, %r39, %r1;
	mul.lo.s32 	%r48, %r37, %r40;
	add.s64 	%rd6, %rd4, -1;
	mov.b32 	%r36, 0;
	setp.gt.s32 	%p3, %r27, 0;
	setp.eq.b32 	%p9, %r8, 0;
	mov.b32 	%r50, %r36;
	bra.uni 	$L__BB0_3;
$L__BB0_6:                              // %._crit_edge23.us
                                        //   in Loop: Header=BB0_3 Depth=1
	.loc	1 42 39                         // group_select.py:42:39
	add.s32 	%r50, %r50, 1;
	add.s32 	%r49, %r49, %r30;
	add.s32 	%r48, %r48, %r30;
	setp.ne.b32 	%p21, %r50, %r26;
	@%p21 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_7;
$L__BB0_3:                              // %.lr.ph22.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_4 Depth 2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 46 37                         // group_select.py:46:37
	add.s32 	%r15, %r50, %r4;
	mov.b32 	%r51, %r36;
	bra.uni 	$L__BB0_4;
$L__BB0_5:                              // %._crit_edge.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 47 38                         // group_select.py:47:38
	add.s32 	%r51, %r51, 32;
	setp.lt.s32 	%p20, %r51, %r30;
	@%p20 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_6;
$L__BB0_4:                              //   Parent Loop BB0_3 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 50 48                         // group_select.py:50:48
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;
$L__BB0_8:                              // %.lr.ph.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 0                           // group_select.py:0
	or.b32 	%r17, %r51, %r6;
	.loc	1 50 48                         // group_select.py:50:48
	mul.wide.s32 	%rd28, %r17, 2;
	add.s64 	%rd15, %rd18, %rd28;
	add.s64 	%rd16, %rd20, %rd28;
	mov.b64 	%rd52, 0;
	setp.lt.s32 	%p8, %r17, %r30;
	mov.b64 	%rd51, %rd3;
	mov.b32 	%r53, %r49;
$L__BB0_9:                              //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 53 33                         // group_select.py:53:33
	// begin inline asm
	mov.u32 %r42, 0x0;
	ld.global.b32 { %r42 }, [ %rd51 + 0 ];
	// end inline asm
	.loc	1 55 35                         // group_select.py:55:35
	cvt.s64.s32 	%rd34, %r42;
	setp.lt.s64 	%p10, %rd52, %rd34;
	.loc	1 57 44                         // group_select.py:57:44
	mad.lo.s32 	%r43, %r7, %r42, %r15;
	mul.lo.s32 	%r44, %r43, %r30;
	.loc	1 61 65                         // group_select.py:61:65
	mul.wide.s32 	%rd35, %r44, 2;
	add.s64 	%rd30, %rd15, %rd35;
	.loc	1 61 99                         // group_select.py:61:99
	and.pred 	%p4, %p8, %p10;
	.loc	1 61 86                         // group_select.py:61:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p4 ld.global.b16 { %rs1 }, [ %rd30 + 0 ];
	// end inline asm
	.loc	1 62 60                         // group_select.py:62:60
	mul.wide.s32 	%rd36, %r53, 2;
	add.s64 	%rd31, %rd15, %rd36;
	.loc	1 62 90                         // group_select.py:62:90
	and.pred 	%p5, %p9, %p4;
	// begin inline asm
	@%p5 st.global.b16 [ %rd31 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 63 65                         // group_select.py:63:65
	add.s64 	%rd32, %rd16, %rd35;
	.loc	1 63 86                         // group_select.py:63:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p4 ld.global.b16 { %rs3 }, [ %rd32 + 0 ];
	// end inline asm
	.loc	1 64 60                         // group_select.py:64:60
	add.s64 	%rd33, %rd16, %rd36;
	.loc	1 64 90                         // group_select.py:64:90
	// begin inline asm
	@%p5 st.global.b16 [ %rd33 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 50 48                         // group_select.py:50:48
	add.s64 	%rd52, %rd52, 1;
	add.s32 	%r53, %r53, %r10;
	add.s64 	%rd51, %rd51, 4;
	setp.eq.b64 	%p11, %rd5, %rd52;
	@%p11 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_9;
$L__BB0_10:                             // %.lr.ph12.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd50, 0;
	mov.b64 	%rd49, %rd6;
	mov.b32 	%r52, %r48;
$L__BB0_11:                             //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd43, %rd50;
	add.s64 	%rd44, %rd4, %rd43;
	.loc	1 69 73                         // group_select.py:69:73
	shl.b64 	%rd45, %rd44, 2;
	add.s64 	%rd38, %rd3, %rd45;
	.loc	1 69 33                         // group_select.py:69:33
	// begin inline asm
	mov.u32 %r45, 0x0;
	ld.global.b32 { %r45 }, [ %rd38 + 0 ];
	// end inline asm
	.loc	1 71 35                         // group_select.py:71:35
	cvt.s64.s32 	%rd46, %r45;
	setp.gt.s64 	%p18, %rd49, %rd46;
	.loc	1 73 44                         // group_select.py:73:44
	mad.lo.s32 	%r46, %r7, %r45, %r15;
	mul.lo.s32 	%r47, %r46, %r30;
	.loc	1 76 65                         // group_select.py:76:65
	mul.wide.s32 	%rd47, %r47, 2;
	add.s64 	%rd39, %rd15, %rd47;
	.loc	1 76 99                         // group_select.py:76:99
	and.pred 	%p12, %p8, %p18;
	.loc	1 76 86                         // group_select.py:76:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p12 ld.global.b16 { %rs5 }, [ %rd39 + 0 ];
	// end inline asm
	.loc	1 77 60                         // group_select.py:77:60
	mul.wide.s32 	%rd48, %r52, 2;
	add.s64 	%rd40, %rd15, %rd48;
	.loc	1 77 90                         // group_select.py:77:90
	and.pred 	%p13, %p9, %p12;
	// begin inline asm
	@%p13 st.global.b16 [ %rd40 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 78 65                         // group_select.py:78:65
	add.s64 	%rd41, %rd16, %rd47;
	.loc	1 78 86                         // group_select.py:78:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p12 ld.global.b16 { %rs7 }, [ %rd41 + 0 ];
	// end inline asm
	.loc	1 79 60                         // group_select.py:79:60
	add.s64 	%rd42, %rd16, %rd48;
	.loc	1 79 90                         // group_select.py:79:90
	// begin inline asm
	@%p13 st.global.b16 [ %rd42 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 66 49                         // group_select.py:66:49
	add.s64 	%rd50, %rd50, 1;
	sub.s32 	%r52, %r52, %r10;
	add.s64 	%rd49, %rd49, -1;
	setp.eq.b64 	%p19, %rd5, %rd50;
	@%p19 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_11;
$L__BB0_7:                              // %._crit_edge26
	.loc	1 42 4                          // group_select.py:42:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/renziyi.6/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 114
.b8 101
.b8 110
.b8 122
.b8 105
.b8 121
.b8 105
.b8 46
.b8 54
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})" ,  // Index 0
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<53>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r26, [_group_cache_select_param_4];
	ld.param.b64 	%rd23, [_group_cache_select_param_1];
$L__tmp0:
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd24, [_group_cache_select_param_2];
	.loc	1 31 29                         // group_select.py:31:29
	mov.u32 	%r33, %ctaid.y;
	ld.param.b64 	%rd25, [_group_cache_select_param_3];
	.loc	1 34 37                         // group_select.py:34:37
	mad.wide.u32 	%rd17, %r33, 4, %rd25;
	.loc	1 34 23                         // group_select.py:34:23
	// begin inline asm
	mov.u32 %r31, 0x0;
	ld.global.b32 { %r31 }, [ %rd17 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	mul.wide.u32 	%rd26, %r32, 8;
	add.s64 	%rd19, %rd23, %rd26;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd18, 0x0;
	ld.global.b64 { %rd18 }, [ %rd19 + 0 ];
	// end inline asm
	.loc	1 36 37                         // group_select.py:36:37
	add.s64 	%rd21, %rd24, %rd26;
	.loc	1 36 20                         // group_select.py:36:20
	// begin inline asm
	mov.u64 %rd20, 0x0;
	ld.global.b64 { %rd20 }, [ %rd21 + 0 ];
	// end inline asm
	.loc	1 42 39                         // group_select.py:42:39
	setp.lt.s32 	%p1, %r26, 1;
	@%p1 bra 	$L__BB0_7;
// %bb.1:                               // %.lr.ph25
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r30, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r30, 1;
	@%p2 bra 	$L__BB0_7;
// %bb.2:                               // %.lr.ph22.us.preheader
	ld.param.b32 	%r29, [_group_cache_select_param_7];
	ld.param.b32 	%r28, [_group_cache_select_param_6];
	ld.param.b32 	%r27, [_group_cache_select_param_5];
	ld.param.b64 	%rd22, [_group_cache_select_param_0];
	mov.u32 	%r1, %ctaid.z;
	mul.lo.s32 	%r34, %r28, %r27;
	mad.lo.s32 	%r3, %r34, %r31, %r1;
	mul.lo.s32 	%r4, %r3, %r29;
	mov.u32 	%r5, %tid.x;
	and.b32 	%r6, %r5, 31;
	mul.lo.s32 	%r35, %r27, %r33;
	mad.wide.s32 	%rd3, %r35, 4, %rd22;
	mul.lo.s32 	%r7, %r29, %r28;
	and.b32 	%r8, %r5, 96;
	.loc	1 47 38                         // group_select.py:47:38
	cvt.s64.s32 	%rd4, %r27;
	cvt.u64.u32 	%rd5, %r27;
	mul.lo.s32 	%r37, %r30, %r29;
	mul.lo.s32 	%r49, %r37, %r3;
	mul.lo.s32 	%r10, %r37, %r28;
	mad.lo.s32 	%r38, %r27, %r31, %r27;
	add.s32 	%r39, %r38, -1;
	mad.lo.s32 	%r40, %r28, %r39, %r1;
	mul.lo.s32 	%r48, %r37, %r40;
	add.s64 	%rd6, %rd4, -1;
	mov.b32 	%r36, 0;
	setp.gt.s32 	%p3, %r27, 0;
	setp.eq.b32 	%p9, %r8, 0;
	mov.b32 	%r50, %r36;
	bra.uni 	$L__BB0_3;
$L__BB0_6:                              // %._crit_edge23.us
                                        //   in Loop: Header=BB0_3 Depth=1
	.loc	1 42 39                         // group_select.py:42:39
	add.s32 	%r50, %r50, 1;
	add.s32 	%r49, %r49, %r30;
	add.s32 	%r48, %r48, %r30;
	setp.ne.b32 	%p21, %r50, %r26;
	@%p21 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_7;
$L__BB0_3:                              // %.lr.ph22.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_4 Depth 2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 46 37                         // group_select.py:46:37
	add.s32 	%r15, %r50, %r4;
	mov.b32 	%r51, %r36;
	bra.uni 	$L__BB0_4;
$L__BB0_5:                              // %._crit_edge.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 47 38                         // group_select.py:47:38
	add.s32 	%r51, %r51, 32;
	setp.lt.s32 	%p20, %r51, %r30;
	@%p20 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_6;
$L__BB0_4:                              //   Parent Loop BB0_3 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 50 48                         // group_select.py:50:48
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;
$L__BB0_8:                              // %.lr.ph.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 0                           // group_select.py:0
	or.b32 	%r17, %r51, %r6;
	.loc	1 50 48                         // group_select.py:50:48
	mul.wide.s32 	%rd28, %r17, 2;
	add.s64 	%rd15, %rd18, %rd28;
	add.s64 	%rd16, %rd20, %rd28;
	mov.b64 	%rd52, 0;
	setp.lt.s32 	%p8, %r17, %r30;
	mov.b64 	%rd51, %rd3;
	mov.b32 	%r53, %r49;
$L__BB0_9:                              //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 53 33                         // group_select.py:53:33
	// begin inline asm
	mov.u32 %r42, 0x0;
	ld.global.b32 { %r42 }, [ %rd51 + 0 ];
	// end inline asm
	.loc	1 55 35                         // group_select.py:55:35
	cvt.s64.s32 	%rd34, %r42;
	setp.lt.s64 	%p10, %rd52, %rd34;
	.loc	1 57 44                         // group_select.py:57:44
	mad.lo.s32 	%r43, %r7, %r42, %r15;
	mul.lo.s32 	%r44, %r43, %r30;
	.loc	1 61 65                         // group_select.py:61:65
	mul.wide.s32 	%rd35, %r44, 2;
	add.s64 	%rd30, %rd15, %rd35;
	.loc	1 61 99                         // group_select.py:61:99
	and.pred 	%p4, %p8, %p10;
	.loc	1 61 86                         // group_select.py:61:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p4 ld.global.b16 { %rs1 }, [ %rd30 + 0 ];
	// end inline asm
	.loc	1 62 60                         // group_select.py:62:60
	mul.wide.s32 	%rd36, %r53, 2;
	add.s64 	%rd31, %rd15, %rd36;
	.loc	1 62 90                         // group_select.py:62:90
	and.pred 	%p5, %p9, %p4;
	// begin inline asm
	@%p5 st.global.b16 [ %rd31 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 63 65                         // group_select.py:63:65
	add.s64 	%rd32, %rd16, %rd35;
	.loc	1 63 86                         // group_select.py:63:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p4 ld.global.b16 { %rs3 }, [ %rd32 + 0 ];
	// end inline asm
	.loc	1 64 60                         // group_select.py:64:60
	add.s64 	%rd33, %rd16, %rd36;
	.loc	1 64 90                         // group_select.py:64:90
	// begin inline asm
	@%p5 st.global.b16 [ %rd33 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 50 48                         // group_select.py:50:48
	add.s64 	%rd52, %rd52, 1;
	add.s32 	%r53, %r53, %r10;
	add.s64 	%rd51, %rd51, 4;
	setp.eq.b64 	%p11, %rd5, %rd52;
	@%p11 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_9;
$L__BB0_10:                             // %.lr.ph12.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd50, 0;
	mov.b64 	%rd49, %rd6;
	mov.b32 	%r52, %r48;
$L__BB0_11:                             //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd43, %rd50;
	add.s64 	%rd44, %rd4, %rd43;
	.loc	1 69 73                         // group_select.py:69:73
	shl.b64 	%rd45, %rd44, 2;
	add.s64 	%rd38, %rd3, %rd45;
	.loc	1 69 33                         // group_select.py:69:33
	// begin inline asm
	mov.u32 %r45, 0x0;
	ld.global.b32 { %r45 }, [ %rd38 + 0 ];
	// end inline asm
	.loc	1 71 35                         // group_select.py:71:35
	cvt.s64.s32 	%rd46, %r45;
	setp.gt.s64 	%p18, %rd49, %rd46;
	.loc	1 73 44                         // group_select.py:73:44
	mad.lo.s32 	%r46, %r7, %r45, %r15;
	mul.lo.s32 	%r47, %r46, %r30;
	.loc	1 76 65                         // group_select.py:76:65
	mul.wide.s32 	%rd47, %r47, 2;
	add.s64 	%rd39, %rd15, %rd47;
	.loc	1 76 99                         // group_select.py:76:99
	and.pred 	%p12, %p8, %p18;
	.loc	1 76 86                         // group_select.py:76:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p12 ld.global.b16 { %rs5 }, [ %rd39 + 0 ];
	// end inline asm
	.loc	1 77 60                         // group_select.py:77:60
	mul.wide.s32 	%rd48, %r52, 2;
	add.s64 	%rd40, %rd15, %rd48;
	.loc	1 77 90                         // group_select.py:77:90
	and.pred 	%p13, %p9, %p12;
	// begin inline asm
	@%p13 st.global.b16 [ %rd40 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 78 65                         // group_select.py:78:65
	add.s64 	%rd41, %rd16, %rd47;
	.loc	1 78 86                         // group_select.py:78:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p12 ld.global.b16 { %rs7 }, [ %rd41 + 0 ];
	// end inline asm
	.loc	1 79 60                         // group_select.py:79:60
	add.s64 	%rd42, %rd16, %rd48;
	.loc	1 79 90                         // group_select.py:79:90
	// begin inline asm
	@%p13 st.global.b16 [ %rd42 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 66 49                         // group_select.py:66:49
	add.s64 	%rd50, %rd50, 1;
	sub.s32 	%r52, %r52, %r10;
	add.s64 	%rd49, %rd49, -1;
	setp.eq.b64 	%p19, %rd5, %rd50;
	@%p19 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_11;
$L__BB0_7:                              // %._crit_edge26
	.loc	1 42 4                          // group_select.py:42:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/renziyi.6/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 114
.b8 101
.b8 110
.b8 122
.b8 105
.b8 121
.b8 105
.b8 46
.b8 54
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})" ,  // Index 1
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<53>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r26, [_group_cache_select_param_4];
	ld.param.b64 	%rd23, [_group_cache_select_param_1];
$L__tmp0:
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd24, [_group_cache_select_param_2];
	.loc	1 31 29                         // group_select.py:31:29
	mov.u32 	%r33, %ctaid.y;
	ld.param.b64 	%rd25, [_group_cache_select_param_3];
	.loc	1 34 37                         // group_select.py:34:37
	mad.wide.u32 	%rd17, %r33, 4, %rd25;
	.loc	1 34 23                         // group_select.py:34:23
	// begin inline asm
	mov.u32 %r31, 0x0;
	ld.global.b32 { %r31 }, [ %rd17 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	mul.wide.u32 	%rd26, %r32, 8;
	add.s64 	%rd19, %rd23, %rd26;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd18, 0x0;
	ld.global.b64 { %rd18 }, [ %rd19 + 0 ];
	// end inline asm
	.loc	1 36 37                         // group_select.py:36:37
	add.s64 	%rd21, %rd24, %rd26;
	.loc	1 36 20                         // group_select.py:36:20
	// begin inline asm
	mov.u64 %rd20, 0x0;
	ld.global.b64 { %rd20 }, [ %rd21 + 0 ];
	// end inline asm
	.loc	1 42 39                         // group_select.py:42:39
	setp.lt.s32 	%p1, %r26, 1;
	@%p1 bra 	$L__BB0_7;
// %bb.1:                               // %.lr.ph25
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r30, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r30, 1;
	@%p2 bra 	$L__BB0_7;
// %bb.2:                               // %.lr.ph22.us.preheader
	ld.param.b32 	%r29, [_group_cache_select_param_7];
	ld.param.b32 	%r28, [_group_cache_select_param_6];
	ld.param.b32 	%r27, [_group_cache_select_param_5];
	ld.param.b64 	%rd22, [_group_cache_select_param_0];
	mov.u32 	%r1, %ctaid.z;
	mul.lo.s32 	%r34, %r28, %r27;
	mad.lo.s32 	%r3, %r34, %r31, %r1;
	mul.lo.s32 	%r4, %r3, %r29;
	mov.u32 	%r5, %tid.x;
	and.b32 	%r6, %r5, 31;
	mul.lo.s32 	%r35, %r27, %r33;
	mad.wide.s32 	%rd3, %r35, 4, %rd22;
	mul.lo.s32 	%r7, %r29, %r28;
	and.b32 	%r8, %r5, 96;
	.loc	1 47 38                         // group_select.py:47:38
	cvt.s64.s32 	%rd4, %r27;
	cvt.u64.u32 	%rd5, %r27;
	mul.lo.s32 	%r37, %r30, %r29;
	mul.lo.s32 	%r49, %r37, %r3;
	mul.lo.s32 	%r10, %r37, %r28;
	mad.lo.s32 	%r38, %r27, %r31, %r27;
	add.s32 	%r39, %r38, -1;
	mad.lo.s32 	%r40, %r28, %r39, %r1;
	mul.lo.s32 	%r48, %r37, %r40;
	add.s64 	%rd6, %rd4, -1;
	mov.b32 	%r36, 0;
	setp.gt.s32 	%p3, %r27, 0;
	setp.eq.b32 	%p9, %r8, 0;
	mov.b32 	%r50, %r36;
	bra.uni 	$L__BB0_3;
$L__BB0_6:                              // %._crit_edge23.us
                                        //   in Loop: Header=BB0_3 Depth=1
	.loc	1 42 39                         // group_select.py:42:39
	add.s32 	%r50, %r50, 1;
	add.s32 	%r49, %r49, %r30;
	add.s32 	%r48, %r48, %r30;
	setp.ne.b32 	%p21, %r50, %r26;
	@%p21 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_7;
$L__BB0_3:                              // %.lr.ph22.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_4 Depth 2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 46 37                         // group_select.py:46:37
	add.s32 	%r15, %r50, %r4;
	mov.b32 	%r51, %r36;
	bra.uni 	$L__BB0_4;
$L__BB0_5:                              // %._crit_edge.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 47 38                         // group_select.py:47:38
	add.s32 	%r51, %r51, 32;
	setp.lt.s32 	%p20, %r51, %r30;
	@%p20 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_6;
$L__BB0_4:                              //   Parent Loop BB0_3 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 50 48                         // group_select.py:50:48
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;
$L__BB0_8:                              // %.lr.ph.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 0                           // group_select.py:0
	or.b32 	%r17, %r51, %r6;
	.loc	1 50 48                         // group_select.py:50:48
	mul.wide.s32 	%rd28, %r17, 2;
	add.s64 	%rd15, %rd18, %rd28;
	add.s64 	%rd16, %rd20, %rd28;
	mov.b64 	%rd52, 0;
	setp.lt.s32 	%p8, %r17, %r30;
	mov.b64 	%rd51, %rd3;
	mov.b32 	%r53, %r49;
$L__BB0_9:                              //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 53 33                         // group_select.py:53:33
	// begin inline asm
	mov.u32 %r42, 0x0;
	ld.global.b32 { %r42 }, [ %rd51 + 0 ];
	// end inline asm
	.loc	1 55 35                         // group_select.py:55:35
	cvt.s64.s32 	%rd34, %r42;
	setp.lt.s64 	%p10, %rd52, %rd34;
	.loc	1 57 44                         // group_select.py:57:44
	mad.lo.s32 	%r43, %r7, %r42, %r15;
	mul.lo.s32 	%r44, %r43, %r30;
	.loc	1 61 65                         // group_select.py:61:65
	mul.wide.s32 	%rd35, %r44, 2;
	add.s64 	%rd30, %rd15, %rd35;
	.loc	1 61 99                         // group_select.py:61:99
	and.pred 	%p4, %p8, %p10;
	.loc	1 61 86                         // group_select.py:61:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p4 ld.global.b16 { %rs1 }, [ %rd30 + 0 ];
	// end inline asm
	.loc	1 62 60                         // group_select.py:62:60
	mul.wide.s32 	%rd36, %r53, 2;
	add.s64 	%rd31, %rd15, %rd36;
	.loc	1 62 90                         // group_select.py:62:90
	and.pred 	%p5, %p9, %p4;
	// begin inline asm
	@%p5 st.global.b16 [ %rd31 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 63 65                         // group_select.py:63:65
	add.s64 	%rd32, %rd16, %rd35;
	.loc	1 63 86                         // group_select.py:63:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p4 ld.global.b16 { %rs3 }, [ %rd32 + 0 ];
	// end inline asm
	.loc	1 64 60                         // group_select.py:64:60
	add.s64 	%rd33, %rd16, %rd36;
	.loc	1 64 90                         // group_select.py:64:90
	// begin inline asm
	@%p5 st.global.b16 [ %rd33 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 50 48                         // group_select.py:50:48
	add.s64 	%rd52, %rd52, 1;
	add.s32 	%r53, %r53, %r10;
	add.s64 	%rd51, %rd51, 4;
	setp.eq.b64 	%p11, %rd5, %rd52;
	@%p11 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_9;
$L__BB0_10:                             // %.lr.ph12.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd50, 0;
	mov.b64 	%rd49, %rd6;
	mov.b32 	%r52, %r48;
$L__BB0_11:                             //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd43, %rd50;
	add.s64 	%rd44, %rd4, %rd43;
	.loc	1 69 73                         // group_select.py:69:73
	shl.b64 	%rd45, %rd44, 2;
	add.s64 	%rd38, %rd3, %rd45;
	.loc	1 69 33                         // group_select.py:69:33
	// begin inline asm
	mov.u32 %r45, 0x0;
	ld.global.b32 { %r45 }, [ %rd38 + 0 ];
	// end inline asm
	.loc	1 71 35                         // group_select.py:71:35
	cvt.s64.s32 	%rd46, %r45;
	setp.gt.s64 	%p18, %rd49, %rd46;
	.loc	1 73 44                         // group_select.py:73:44
	mad.lo.s32 	%r46, %r7, %r45, %r15;
	mul.lo.s32 	%r47, %r46, %r30;
	.loc	1 76 65                         // group_select.py:76:65
	mul.wide.s32 	%rd47, %r47, 2;
	add.s64 	%rd39, %rd15, %rd47;
	.loc	1 76 99                         // group_select.py:76:99
	and.pred 	%p12, %p8, %p18;
	.loc	1 76 86                         // group_select.py:76:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p12 ld.global.b16 { %rs5 }, [ %rd39 + 0 ];
	// end inline asm
	.loc	1 77 60                         // group_select.py:77:60
	mul.wide.s32 	%rd48, %r52, 2;
	add.s64 	%rd40, %rd15, %rd48;
	.loc	1 77 90                         // group_select.py:77:90
	and.pred 	%p13, %p9, %p12;
	// begin inline asm
	@%p13 st.global.b16 [ %rd40 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 78 65                         // group_select.py:78:65
	add.s64 	%rd41, %rd16, %rd47;
	.loc	1 78 86                         // group_select.py:78:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p12 ld.global.b16 { %rs7 }, [ %rd41 + 0 ];
	// end inline asm
	.loc	1 79 60                         // group_select.py:79:60
	add.s64 	%rd42, %rd16, %rd48;
	.loc	1 79 90                         // group_select.py:79:90
	// begin inline asm
	@%p13 st.global.b16 [ %rd42 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 66 49                         // group_select.py:66:49
	add.s64 	%rd50, %rd50, 1;
	sub.s32 	%r52, %r52, %r10;
	add.s64 	%rd49, %rd49, -1;
	setp.eq.b64 	%p19, %rd5, %rd50;
	@%p19 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_11;
$L__BB0_7:                              // %._crit_edge26
	.loc	1 42 4                          // group_select.py:42:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/renziyi.6/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 114
.b8 101
.b8 110
.b8 122
.b8 105
.b8 121
.b8 105
.b8 46
.b8 54
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})" ,  // Index 2
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u64 .ptr .global .align 1 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u32 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10
)
.reqntid 128
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<53>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r26, [_group_cache_select_param_4];
	ld.param.b64 	%rd23, [_group_cache_select_param_1];
$L__tmp0:
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd24, [_group_cache_select_param_2];
	.loc	1 31 29                         // group_select.py:31:29
	mov.u32 	%r33, %ctaid.y;
	ld.param.b64 	%rd25, [_group_cache_select_param_3];
	.loc	1 34 37                         // group_select.py:34:37
	mad.wide.u32 	%rd17, %r33, 4, %rd25;
	.loc	1 34 23                         // group_select.py:34:23
	// begin inline asm
	mov.u32 %r31, 0x0;
	ld.global.b32 { %r31 }, [ %rd17 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	mul.wide.u32 	%rd26, %r32, 8;
	add.s64 	%rd19, %rd23, %rd26;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd18, 0x0;
	ld.global.b64 { %rd18 }, [ %rd19 + 0 ];
	// end inline asm
	.loc	1 36 37                         // group_select.py:36:37
	add.s64 	%rd21, %rd24, %rd26;
	.loc	1 36 20                         // group_select.py:36:20
	// begin inline asm
	mov.u64 %rd20, 0x0;
	ld.global.b64 { %rd20 }, [ %rd21 + 0 ];
	// end inline asm
	.loc	1 42 39                         // group_select.py:42:39
	setp.lt.s32 	%p1, %r26, 1;
	@%p1 bra 	$L__BB0_7;
// %bb.1:                               // %.lr.ph25
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r30, [_group_cache_select_param_8];
	setp.lt.s32 	%p2, %r30, 1;
	@%p2 bra 	$L__BB0_7;
// %bb.2:                               // %.lr.ph22.us.preheader
	ld.param.b32 	%r29, [_group_cache_select_param_7];
	ld.param.b32 	%r28, [_group_cache_select_param_6];
	ld.param.b32 	%r27, [_group_cache_select_param_5];
	ld.param.b64 	%rd22, [_group_cache_select_param_0];
	mov.u32 	%r1, %ctaid.z;
	mul.lo.s32 	%r34, %r28, %r27;
	mad.lo.s32 	%r3, %r34, %r31, %r1;
	mul.lo.s32 	%r4, %r3, %r29;
	mov.u32 	%r5, %tid.x;
	and.b32 	%r6, %r5, 31;
	mul.lo.s32 	%r35, %r27, %r33;
	mad.wide.s32 	%rd3, %r35, 4, %rd22;
	mul.lo.s32 	%r7, %r29, %r28;
	and.b32 	%r8, %r5, 96;
	.loc	1 47 38                         // group_select.py:47:38
	cvt.s64.s32 	%rd4, %r27;
	cvt.u64.u32 	%rd5, %r27;
	mul.lo.s32 	%r37, %r30, %r29;
	mul.lo.s32 	%r49, %r37, %r3;
	mul.lo.s32 	%r10, %r37, %r28;
	mad.lo.s32 	%r38, %r27, %r31, %r27;
	add.s32 	%r39, %r38, -1;
	mad.lo.s32 	%r40, %r28, %r39, %r1;
	mul.lo.s32 	%r48, %r37, %r40;
	add.s64 	%rd6, %rd4, -1;
	mov.b32 	%r36, 0;
	setp.gt.s32 	%p3, %r27, 0;
	setp.eq.b32 	%p9, %r8, 0;
	mov.b32 	%r50, %r36;
	bra.uni 	$L__BB0_3;
$L__BB0_6:                              // %._crit_edge23.us
                                        //   in Loop: Header=BB0_3 Depth=1
	.loc	1 42 39                         // group_select.py:42:39
	add.s32 	%r50, %r50, 1;
	add.s32 	%r49, %r49, %r30;
	add.s32 	%r48, %r48, %r30;
	setp.ne.b32 	%p21, %r50, %r26;
	@%p21 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_7;
$L__BB0_3:                              // %.lr.ph22.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_4 Depth 2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 46 37                         // group_select.py:46:37
	add.s32 	%r15, %r50, %r4;
	mov.b32 	%r51, %r36;
	bra.uni 	$L__BB0_4;
$L__BB0_5:                              // %._crit_edge.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 47 38                         // group_select.py:47:38
	add.s32 	%r51, %r51, 32;
	setp.lt.s32 	%p20, %r51, %r30;
	@%p20 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_6;
$L__BB0_4:                              //   Parent Loop BB0_3 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 50 48                         // group_select.py:50:48
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;
$L__BB0_8:                              // %.lr.ph.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 0                           // group_select.py:0
	or.b32 	%r17, %r51, %r6;
	.loc	1 50 48                         // group_select.py:50:48
	mul.wide.s32 	%rd28, %r17, 2;
	add.s64 	%rd15, %rd18, %rd28;
	add.s64 	%rd16, %rd20, %rd28;
	mov.b64 	%rd52, 0;
	setp.lt.s32 	%p8, %r17, %r30;
	mov.b64 	%rd51, %rd3;
	mov.b32 	%r53, %r49;
$L__BB0_9:                              //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 53 33                         // group_select.py:53:33
	// begin inline asm
	mov.u32 %r42, 0x0;
	ld.global.b32 { %r42 }, [ %rd51 + 0 ];
	// end inline asm
	.loc	1 55 35                         // group_select.py:55:35
	cvt.s64.s32 	%rd34, %r42;
	setp.lt.s64 	%p10, %rd52, %rd34;
	.loc	1 57 44                         // group_select.py:57:44
	mad.lo.s32 	%r43, %r7, %r42, %r15;
	mul.lo.s32 	%r44, %r43, %r30;
	.loc	1 61 65                         // group_select.py:61:65
	mul.wide.s32 	%rd35, %r44, 2;
	add.s64 	%rd30, %rd15, %rd35;
	.loc	1 61 99                         // group_select.py:61:99
	and.pred 	%p4, %p8, %p10;
	.loc	1 61 86                         // group_select.py:61:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p4 ld.global.b16 { %rs1 }, [ %rd30 + 0 ];
	// end inline asm
	.loc	1 62 60                         // group_select.py:62:60
	mul.wide.s32 	%rd36, %r53, 2;
	add.s64 	%rd31, %rd15, %rd36;
	.loc	1 62 90                         // group_select.py:62:90
	and.pred 	%p5, %p9, %p4;
	// begin inline asm
	@%p5 st.global.b16 [ %rd31 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 63 65                         // group_select.py:63:65
	add.s64 	%rd32, %rd16, %rd35;
	.loc	1 63 86                         // group_select.py:63:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p4 ld.global.b16 { %rs3 }, [ %rd32 + 0 ];
	// end inline asm
	.loc	1 64 60                         // group_select.py:64:60
	add.s64 	%rd33, %rd16, %rd36;
	.loc	1 64 90                         // group_select.py:64:90
	// begin inline asm
	@%p5 st.global.b16 [ %rd33 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 50 48                         // group_select.py:50:48
	add.s64 	%rd52, %rd52, 1;
	add.s32 	%r53, %r53, %r10;
	add.s64 	%rd51, %rd51, 4;
	setp.eq.b64 	%p11, %rd5, %rd52;
	@%p11 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_9;
$L__BB0_10:                             // %.lr.ph12.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd50, 0;
	mov.b64 	%rd49, %rd6;
	mov.b32 	%r52, %r48;
$L__BB0_11:                             //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd43, %rd50;
	add.s64 	%rd44, %rd4, %rd43;
	.loc	1 69 73                         // group_select.py:69:73
	shl.b64 	%rd45, %rd44, 2;
	add.s64 	%rd38, %rd3, %rd45;
	.loc	1 69 33                         // group_select.py:69:33
	// begin inline asm
	mov.u32 %r45, 0x0;
	ld.global.b32 { %r45 }, [ %rd38 + 0 ];
	// end inline asm
	.loc	1 71 35                         // group_select.py:71:35
	cvt.s64.s32 	%rd46, %r45;
	setp.gt.s64 	%p18, %rd49, %rd46;
	.loc	1 73 44                         // group_select.py:73:44
	mad.lo.s32 	%r46, %r7, %r45, %r15;
	mul.lo.s32 	%r47, %r46, %r30;
	.loc	1 76 65                         // group_select.py:76:65
	mul.wide.s32 	%rd47, %r47, 2;
	add.s64 	%rd39, %rd15, %rd47;
	.loc	1 76 99                         // group_select.py:76:99
	and.pred 	%p12, %p8, %p18;
	.loc	1 76 86                         // group_select.py:76:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p12 ld.global.b16 { %rs5 }, [ %rd39 + 0 ];
	// end inline asm
	.loc	1 77 60                         // group_select.py:77:60
	mul.wide.s32 	%rd48, %r52, 2;
	add.s64 	%rd40, %rd15, %rd48;
	.loc	1 77 90                         // group_select.py:77:90
	and.pred 	%p13, %p9, %p12;
	// begin inline asm
	@%p13 st.global.b16 [ %rd40 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 78 65                         // group_select.py:78:65
	add.s64 	%rd41, %rd16, %rd47;
	.loc	1 78 86                         // group_select.py:78:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p12 ld.global.b16 { %rs7 }, [ %rd41 + 0 ];
	// end inline asm
	.loc	1 79 60                         // group_select.py:79:60
	add.s64 	%rd42, %rd16, %rd48;
	.loc	1 79 90                         // group_select.py:79:90
	// begin inline asm
	@%p13 st.global.b16 [ %rd42 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 66 49                         // group_select.py:66:49
	add.s64 	%rd50, %rd50, 1;
	sub.s32 	%r52, %r52, %r10;
	add.s64 	%rd49, %rd49, -1;
	setp.eq.b64 	%p19, %rd5, %rd50;
	@%p19 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_11;
$L__BB0_7:                              // %._crit_edge26
	.loc	1 42 4                          // group_select.py:42:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/renziyi.6/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 114
.b8 101
.b8 110
.b8 122
.b8 105
.b8 121
.b8 105
.b8 46
.b8 54
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})" ,  // Index 3
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	_group_cache_select     // -- Begin function _group_cache_select
                                        // @_group_cache_select
.visible .entry _group_cache_select(
	.param .u32 _group_cache_select_param_0,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_1,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_2,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_3,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_4,
	.param .u32 _group_cache_select_param_5,
	.param .u32 _group_cache_select_param_6,
	.param .u32 _group_cache_select_param_7,
	.param .u32 _group_cache_select_param_8,
	.param .u32 _group_cache_select_param_9,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_10,
	.param .u64 .ptr .global .align 1 _group_cache_select_param_11
)
.reqntid 128
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<9>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<53>;
	.loc	1 13 0                          // group_select.py:13:0
$L__func_begin0:
	.loc	1 13 0                          // group_select.py:13:0

// %bb.0:
	ld.param.b32 	%r26, [_group_cache_select_param_5];
$L__tmp0:
	.loc	1 30 29                         // group_select.py:30:29
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd23, [_group_cache_select_param_2];
	.loc	1 31 29                         // group_select.py:31:29
	mov.u32 	%r33, %ctaid.y;
	ld.param.b64 	%rd24, [_group_cache_select_param_3];
	ld.param.b64 	%rd25, [_group_cache_select_param_4];
	.loc	1 34 37                         // group_select.py:34:37
	mad.wide.u32 	%rd17, %r33, 4, %rd25;
	.loc	1 34 23                         // group_select.py:34:23
	// begin inline asm
	mov.u32 %r31, 0x0;
	ld.global.b32 { %r31 }, [ %rd17 + 0 ];
	// end inline asm
	.loc	1 35 37                         // group_select.py:35:37
	mul.wide.u32 	%rd26, %r32, 8;
	add.s64 	%rd19, %rd23, %rd26;
	.loc	1 35 20                         // group_select.py:35:20
	// begin inline asm
	mov.u64 %rd18, 0x0;
	ld.global.b64 { %rd18 }, [ %rd19 + 0 ];
	// end inline asm
	.loc	1 36 37                         // group_select.py:36:37
	add.s64 	%rd21, %rd24, %rd26;
	.loc	1 36 20                         // group_select.py:36:20
	// begin inline asm
	mov.u64 %rd20, 0x0;
	ld.global.b64 { %rd20 }, [ %rd21 + 0 ];
	// end inline asm
	.loc	1 42 39                         // group_select.py:42:39
	setp.lt.s32 	%p1, %r26, 1;
	@%p1 bra 	$L__BB0_7;
// %bb.1:                               // %.lr.ph25
	.loc	1 0 39                          // group_select.py:0:39
	ld.param.b32 	%r30, [_group_cache_select_param_9];
	setp.lt.s32 	%p2, %r30, 1;
	@%p2 bra 	$L__BB0_7;
// %bb.2:                               // %.lr.ph22.us.preheader
	ld.param.b32 	%r29, [_group_cache_select_param_8];
	ld.param.b32 	%r28, [_group_cache_select_param_7];
	ld.param.b32 	%r27, [_group_cache_select_param_6];
	ld.param.b64 	%rd22, [_group_cache_select_param_1];
	mov.u32 	%r1, %ctaid.z;
	mul.lo.s32 	%r34, %r28, %r27;
	mad.lo.s32 	%r3, %r34, %r31, %r1;
	mul.lo.s32 	%r4, %r3, %r29;
	mov.u32 	%r5, %tid.x;
	and.b32 	%r6, %r5, 31;
	mul.lo.s32 	%r35, %r27, %r33;
	mad.wide.s32 	%rd3, %r35, 4, %rd22;
	mul.lo.s32 	%r7, %r29, %r28;
	and.b32 	%r8, %r5, 96;
	.loc	1 47 38                         // group_select.py:47:38
	cvt.s64.s32 	%rd4, %r27;
	cvt.u64.u32 	%rd5, %r27;
	mul.lo.s32 	%r37, %r30, %r29;
	mul.lo.s32 	%r49, %r37, %r3;
	mul.lo.s32 	%r10, %r37, %r28;
	mad.lo.s32 	%r38, %r27, %r31, %r27;
	add.s32 	%r39, %r38, -1;
	mad.lo.s32 	%r40, %r28, %r39, %r1;
	mul.lo.s32 	%r48, %r37, %r40;
	add.s64 	%rd6, %rd4, -1;
	mov.b32 	%r36, 0;
	setp.gt.s32 	%p3, %r27, 0;
	setp.eq.b32 	%p9, %r8, 0;
	mov.b32 	%r50, %r36;
	bra.uni 	$L__BB0_3;
$L__BB0_6:                              // %._crit_edge23.us
                                        //   in Loop: Header=BB0_3 Depth=1
	.loc	1 42 39                         // group_select.py:42:39
	add.s32 	%r50, %r50, 1;
	add.s32 	%r49, %r49, %r30;
	add.s32 	%r48, %r48, %r30;
	setp.ne.b32 	%p21, %r50, %r26;
	@%p21 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_7;
$L__BB0_3:                              // %.lr.ph22.us
                                        // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_4 Depth 2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 46 37                         // group_select.py:46:37
	add.s32 	%r15, %r50, %r4;
	mov.b32 	%r51, %r36;
	bra.uni 	$L__BB0_4;
$L__BB0_5:                              // %._crit_edge.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 47 38                         // group_select.py:47:38
	add.s32 	%r51, %r51, 32;
	setp.lt.s32 	%p20, %r51, %r30;
	@%p20 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_6;
$L__BB0_4:                              //   Parent Loop BB0_3 Depth=1
                                        // =>  This Loop Header: Depth=2
                                        //       Child Loop BB0_9 Depth 3
                                        //       Child Loop BB0_11 Depth 3
	.loc	1 50 48                         // group_select.py:50:48
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;
$L__BB0_8:                              // %.lr.ph.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 0                           // group_select.py:0
	or.b32 	%r17, %r51, %r6;
	.loc	1 50 48                         // group_select.py:50:48
	mul.wide.s32 	%rd28, %r17, 2;
	add.s64 	%rd15, %rd18, %rd28;
	add.s64 	%rd16, %rd20, %rd28;
	mov.b64 	%rd52, 0;
	setp.lt.s32 	%p8, %r17, %r30;
	mov.b64 	%rd51, %rd3;
	mov.b32 	%r53, %r49;
$L__BB0_9:                              //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	.loc	1 53 33                         // group_select.py:53:33
	// begin inline asm
	mov.u32 %r42, 0x0;
	ld.global.b32 { %r42 }, [ %rd51 + 0 ];
	// end inline asm
	.loc	1 55 35                         // group_select.py:55:35
	cvt.s64.s32 	%rd34, %r42;
	setp.lt.s64 	%p10, %rd52, %rd34;
	.loc	1 57 44                         // group_select.py:57:44
	mad.lo.s32 	%r43, %r7, %r42, %r15;
	mul.lo.s32 	%r44, %r43, %r30;
	.loc	1 61 65                         // group_select.py:61:65
	mul.wide.s32 	%rd35, %r44, 2;
	add.s64 	%rd30, %rd15, %rd35;
	.loc	1 61 99                         // group_select.py:61:99
	and.pred 	%p4, %p8, %p10;
	.loc	1 61 86                         // group_select.py:61:86
	// begin inline asm
	mov.u16 %rs1, 0x0;
	@%p4 ld.global.b16 { %rs1 }, [ %rd30 + 0 ];
	// end inline asm
	.loc	1 62 60                         // group_select.py:62:60
	mul.wide.s32 	%rd36, %r53, 2;
	add.s64 	%rd31, %rd15, %rd36;
	.loc	1 62 90                         // group_select.py:62:90
	and.pred 	%p5, %p9, %p4;
	// begin inline asm
	@%p5 st.global.b16 [ %rd31 + 0 ], { %rs1 };
	// end inline asm
	.loc	1 63 65                         // group_select.py:63:65
	add.s64 	%rd32, %rd16, %rd35;
	.loc	1 63 86                         // group_select.py:63:86
	// begin inline asm
	mov.u16 %rs3, 0x0;
	@%p4 ld.global.b16 { %rs3 }, [ %rd32 + 0 ];
	// end inline asm
	.loc	1 64 60                         // group_select.py:64:60
	add.s64 	%rd33, %rd16, %rd36;
	.loc	1 64 90                         // group_select.py:64:90
	// begin inline asm
	@%p5 st.global.b16 [ %rd33 + 0 ], { %rs3 };
	// end inline asm
	.loc	1 50 48                         // group_select.py:50:48
	add.s64 	%rd52, %rd52, 1;
	add.s32 	%r53, %r53, %r10;
	add.s64 	%rd51, %rd51, 4;
	setp.eq.b64 	%p11, %rd5, %rd52;
	@%p11 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_9;
$L__BB0_10:                             // %.lr.ph12.us
                                        //   in Loop: Header=BB0_4 Depth=2
	.loc	1 0 48                          // group_select.py:0:48
	mov.b64 	%rd50, 0;
	mov.b64 	%rd49, %rd6;
	mov.b32 	%r52, %r48;
$L__BB0_11:                             //   Parent Loop BB0_3 Depth=1
                                        //     Parent Loop BB0_4 Depth=2
                                        // =>    This Inner Loop Header: Depth=3
	not.b64 	%rd43, %rd50;
	add.s64 	%rd44, %rd4, %rd43;
	.loc	1 69 73                         // group_select.py:69:73
	shl.b64 	%rd45, %rd44, 2;
	add.s64 	%rd38, %rd3, %rd45;
	.loc	1 69 33                         // group_select.py:69:33
	// begin inline asm
	mov.u32 %r45, 0x0;
	ld.global.b32 { %r45 }, [ %rd38 + 0 ];
	// end inline asm
	.loc	1 71 35                         // group_select.py:71:35
	cvt.s64.s32 	%rd46, %r45;
	setp.gt.s64 	%p18, %rd49, %rd46;
	.loc	1 73 44                         // group_select.py:73:44
	mad.lo.s32 	%r46, %r7, %r45, %r15;
	mul.lo.s32 	%r47, %r46, %r30;
	.loc	1 76 65                         // group_select.py:76:65
	mul.wide.s32 	%rd47, %r47, 2;
	add.s64 	%rd39, %rd15, %rd47;
	.loc	1 76 99                         // group_select.py:76:99
	and.pred 	%p12, %p8, %p18;
	.loc	1 76 86                         // group_select.py:76:86
	// begin inline asm
	mov.u16 %rs5, 0x0;
	@%p12 ld.global.b16 { %rs5 }, [ %rd39 + 0 ];
	// end inline asm
	.loc	1 77 60                         // group_select.py:77:60
	mul.wide.s32 	%rd48, %r52, 2;
	add.s64 	%rd40, %rd15, %rd48;
	.loc	1 77 90                         // group_select.py:77:90
	and.pred 	%p13, %p9, %p12;
	// begin inline asm
	@%p13 st.global.b16 [ %rd40 + 0 ], { %rs5 };
	// end inline asm
	.loc	1 78 65                         // group_select.py:78:65
	add.s64 	%rd41, %rd16, %rd47;
	.loc	1 78 86                         // group_select.py:78:86
	// begin inline asm
	mov.u16 %rs7, 0x0;
	@%p12 ld.global.b16 { %rs7 }, [ %rd41 + 0 ];
	// end inline asm
	.loc	1 79 60                         // group_select.py:79:60
	add.s64 	%rd42, %rd16, %rd48;
	.loc	1 79 90                         // group_select.py:79:90
	// begin inline asm
	@%p13 st.global.b16 [ %rd42 + 0 ], { %rs7 };
	// end inline asm
	.loc	1 66 49                         // group_select.py:66:49
	add.s64 	%rd50, %rd50, 1;
	sub.s32 	%r52, %r52, %r10;
	add.s64 	%rd49, %rd49, -1;
	setp.eq.b64 	%p19, %rd5, %rd50;
	@%p19 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_11;
$L__BB0_7:                              // %._crit_edge26
	.loc	1 42 4                          // group_select.py:42:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/renziyi.6/xattention_gpu/group_select/group_select.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 88                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x51 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 103                                 // DW_AT_name
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 114
.b8 101
.b8 110
.b8 122
.b8 105
.b8 121
.b8 105
.b8 46
.b8 54
.b8 47
.b8 120
.b8 97
.b8 116
.b8 116
.b8 101
.b8 110
.b8 116
.b8 105
.b8 111
.b8 110
.b8 95
.b8 103
.b8 112
.b8 117
.b8 47
.b8 103
.b8 114
.b8 111
.b8 117
.b8 112
.b8 95
.b8 115
.b8 101
.b8 108
.b8 101
.b8 99
.b8 116
.b8 0
	}
	.section	.debug_macinfo	{	})"    // Index 4
    };
    
// Real 6-dimensional input configurations for group_cache_select
// [BATCH_SIZE, BEAM_SIZE, HEAD_NUM, HEAD_DIM, LAYER_NUM, MAX_DECODE_STEP]
constexpr std::array<std::array<int, 6>, 5> GROUP_CACHE_SELECT_SM_90_bf16_REAL_DIMS = {{
    {1, 128, 2, 2, 1, 3}, {1, 256, 2, 2, 1, 3}, {1, 512, 2, 2, 1, 3}, {1, 1024, 2, 2, 1, 3}, {1, 2048, 2, 2, 32, 3}
}};
