
#pragma once
#include <array>
constexpr const char* simple_tma_copy_kernel_sm_90_bf16 = R"(simple_tma_copy_kernel)";
constexpr std::array<std::array<int, 2>, 1> simple_tma_copy_kernel_sm_90_bf16_INPUT_DIM_ARRAY = {{ 
    { 2048, 1024 }   // Index 0
    }};
constexpr std::array<int, 1> simple_tma_copy_kernel_sm_90_bf16_BLOCK_M_ARRAY{ 64 };
constexpr std::array<int, 1> simple_tma_copy_kernel_sm_90_bf16_BLOCK_N_ARRAY{ 64 };
constexpr std::array<int, 1> simple_tma_copy_kernel_sm_90_bf16_BLOCK_K_ARRAY{ 64 };
constexpr std::array<int, 1> simple_tma_copy_kernel_sm_90_bf16_SHARED_MEM_BYTES{ 8200 };
constexpr std::array<const char*, 1> simple_tma_copy_kernel_sm_90_bf16_PTX_ARRAY = {
    R"(//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_90a
.address_size 64

	// .globl	simple_tma_copy_kernel  // -- Begin function simple_tma_copy_kernel
.extern .shared .align 16 .b8 global_smem[];
                                        // @simple_tma_copy_kernel
.visible .entry simple_tma_copy_kernel(
	.param .align 64 .b8 simple_tma_copy_kernel_param_0[128],
	.param .u32 simple_tma_copy_kernel_param_1,
	.param .u32 simple_tma_copy_kernel_param_2,
	.param .u64 simple_tma_copy_kernel_param_3,
	.param .u64 simple_tma_copy_kernel_param_4,
	.param .align 64 .b8 simple_tma_copy_kernel_param_5[128],
	.param .u32 simple_tma_copy_kernel_param_6,
	.param .u32 simple_tma_copy_kernel_param_7,
	.param .u64 simple_tma_copy_kernel_param_8,
	.param .u64 simple_tma_copy_kernel_param_9,
	.param .u32 simple_tma_copy_kernel_param_10,
	.param .u32 simple_tma_copy_kernel_param_11,
	.param .u64 .ptr .global .align 1 simple_tma_copy_kernel_param_12,
	.param .u64 .ptr .global .align 1 simple_tma_copy_kernel_param_13
)
.reqntid 128
{
	.reg .pred 	%p<9>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<5>;
	.loc	1 75 0                          // tma_copy.py:75:0
$L__func_begin0:
	.loc	1 75 0                          // tma_copy.py:75:0

// %bb.0:
	mov.b64 	%rd3, simple_tma_copy_kernel_param_0;
	mov.b64 	%rd4, simple_tma_copy_kernel_param_5;
$L__tmp0:
	.loc	1 88 24                         // tma_copy.py:88:24
	cvta.param.u64 	%rd2, %rd4;
	cvta.param.u64 	%rd1, %rd3;
	mov.u32 	%r13, %ctaid.x;
	.loc	1 89 24                         // tma_copy.py:89:24
	mov.u32 	%r14, %ctaid.y;
	.loc	1 92 20                         // tma_copy.py:92:20
	shl.b32 	%r5, %r13, 6;
	.loc	1 93 20                         // tma_copy.py:93:20
	shl.b32 	%r4, %r14, 6;
	.loc	1 97 25                         // tma_copy.py:97:25
	mov.u32 	%r15, %tid.x;
	setp.eq.b32 	%p1, %r15, 0;
	mov.b32 	%r3, global_smem;
	add.s32 	%r1, %r3, 8192;
	// begin inline asm
	@%p1 mbarrier.init.shared::cta.b64 [%r1], 1;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p1 mbarrier.arrive.expect_tx.shared.b64 _, [%r1], 8192;
	// end inline asm
	bar.sync 	0;
	elect.sync 	%r16|%p6, -1;
	setp.lt.u32 	%p7, %r15, 32;
	and.pred 	%p3, %p7, %p6;
	// begin inline asm
	@%p3 cp.async.bulk.tensor.2d.shared::cluster.global.mbarrier::complete_tx::bytes [%r3], [%rd1, {%r4, %r5}], [%r1];
	// end inline asm
	bar.sync 	0;
	mov.b32 	%r8, 0;
	// begin inline asm
	
{
	.reg .pred complete;
	waitLoop:
	mbarrier.try_wait.parity.shared.b64 complete, [%r1], %r8;
	@!complete bra.uni waitLoop;
}

	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p1 mbarrier.inval.shared::cta.b64 [%r1];
	// end inline asm
	.loc	1 100 40                        // tma_copy.py:100:40
	// begin inline asm
	fence.proxy.async.shared::cta;
	// end inline asm
	elect.sync 	%r17|%p8, -1;
	and.pred 	%p5, %p7, %p8;
	// begin inline asm
	@%p5 cp.async.bulk.tensor.2d.global.shared::cta.bulk_group [%rd2, {%r4, %r5}], [%r3];
	// end inline asm
	cp.async.bulk.commit_group;
	cp.async.bulk.wait_group.read 	0;
	bar.sync 	0;
	.loc	1 100 2                         // tma_copy.py:100:2
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/export/home/wangyifan/Code/triton_kernel/xllm/src/kernels/triton/moe/triton_kernels/tma_copy.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 118                                // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x6f DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 116                                 // DW_AT_name
.b8 109
.b8 97
.b8 95
.b8 99
.b8 111
.b8 112
.b8 121
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 101
.b8 120
.b8 112
.b8 111
.b8 114
.b8 116
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 119
.b8 97
.b8 110
.b8 103
.b8 121
.b8 105
.b8 102
.b8 97
.b8 110
.b8 47
.b8 67
.b8 111
.b8 100
.b8 101
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 47
.b8 120
.b8 108
.b8 108
.b8 109
.b8 47
.b8 115
.b8 114
.b8 99
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 47
.b8 109
.b8 111
.b8 101
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
	}
	.section	.debug_macinfo	{	}
)"    // Index 0
    };
    